# Generated by Django 4.0.2 on 2022-04-20 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dprt', models.IntegerField()),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.IntegerField()),
                ('dprt', models.IntegerField()),
                ('Class', models.IntegerField()),
                ('day', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=20, null=True)),
                ('Subject', models.CharField(max_length=30)),
                ('Qualifications', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Photo', models.ImageField(blank=True, default='images/example3.jpg', null=True, upload_to='images/')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=20, null=True)),
                ('Phone_number', models.CharField(max_length=10)),
                ('DoB', models.DateField(null=True)),
                ('Photo', models.ImageField(blank=True, default='images/example3.jpg', null=True, upload_to='images/')),
                ('Parent_name', models.CharField(max_length=30)),
                ('Contact_number', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dutty', models.CharField(max_length=20, null=True)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Photo', models.ImageField(blank=True, default='images/example3.jpg', null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='gallery/')),
                ('disc', models.CharField(max_length=1000)),
                ('created', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('course_fee', models.JSONField(default=list)),
                ('HOD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sitemanager.teachers')),
                ('teachers', models.ManyToManyField(related_name='teachers', to='sitemanager.Teachers')),
            ],
        ),
    ]
