# Generated by Django 4.0.2 on 2022-04-04 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=20, null=True)),
                ('Subject', models.CharField(max_length=30)),
                ('Qualifications', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Photo', models.ImageField(blank=True, default='images/example3.jpg', null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=20, null=True)),
                ('Phone_number', models.CharField(max_length=10)),
                ('DoB', models.DateField(null=True)),
                ('Photo', models.ImageField(blank=True, default='images/example3.jpg', null=True, upload_to='images/')),
                ('Parent_name', models.CharField(max_length=30)),
                ('Contact_number', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dutty', models.CharField(max_length=20, null=True)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Photo', models.ImageField(blank=True, default='images/example3.jpg', null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
