# Generated by Django 4.0.2 on 2022-04-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0003_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
