# Generated by Django 4.0.2 on 2022-04-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0004_gallery_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('course_fee', models.JSONField(default=list)),
                ('HOD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sitemanager.teachers')),
                ('teachers', models.ManyToManyField(related_name='teachers', to='sitemanager.Teachers')),
            ],
        ),
    ]
