# Generated by Django 4.0.2 on 2022-04-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0005_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.IntegerField()),
                ('dprt', models.IntegerField()),
                ('Class', models.IntegerField()),
                ('day', models.JSONField(default=dict)),
            ],
        ),
    ]
