# Generated by Django 4.0.2 on 2022-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0006_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dprt', models.IntegerField()),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
